name: gestionbiblioteck
description: "Application de gestion de bibliothèque"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0             # types partagés (Database, ConflictAlgorithm...) utilisés par les DAO
  sqflite_common_ffi: ^2.3.0  # backend SQLite desktop
  sqlite3_flutter_libs: ^0.5.0   # fournit sqlite3.dll pour Windows
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.6
  bcrypt: ^1.1.3
  
